### ISSUE TITLE
Qt camera

### ISSUE THREAD

**Issue by Wei-Qing-Du** [G-Motivation/licensePlate#10]
Hi All,

I had already added the camera in the qt window. Now I confirmed it could work on the Windows OS. Please download qt 5.
Would you please check it on the Mac OS? Thank you.

**Comment by yaodehaung** [comment]
https://medium.com/delightlearner/qt-development-%E5%A6%82%E4%BD%95%E7%94%A8-qt-%E9%96%8B%E5%95%9F%E6%94%9D%E5%BD%B1%E6%A9%9F%E4%B8%A6%E9%A1%AF%E7%A4%BA%E7%95%AB%E9%9D%A2-use-qt-to-create-a-program-to-display-live-stream-from-webcam-f84dd9a1206e
